config/routes.rb
Rails.application.routes.draw do
  get "models/index"
  get "models/show"
  resources :comments
  get "users/index"
  get "users/show"
  devise_for :users

  get "counter", to: "counter#show"
  resources :posts
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  def self.seed_comments
    users = User.all
    posts = Post.all

    users.each do |u|
      uname = u.email.split("@").first
      posts.each do |p|
        u.comments.create post_id: p.id,
                          body: "#{uname} says - nice"
      end
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  def self.seed_posts
    users = User.all

    users.each do |u|
      uname = u.email.split("@").first
      u.posts.create title: "#{uname} says",
                     body:  "#{uname} has an idea"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  def self.seed_users
    usnx = "matthew mark luke john".split(' ')
    usnx.each do |un|
      uemail = "#{un}@example.com"
      next if User.where(email: uemail).present?

      u = User.new
      u.email = uemail
      u.password = "secret"
      u.save
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy!
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :body)
    end
end

app/controllers/counter_controller.rb
class CounterController < ApplicationController
  def show
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    Rails.application.eager_load!
    @descendants = ApplicationRecord.descendants
  end

  def show
    Rails.application.eager_load!
    @descendants = ApplicationRecord.descendants
    @current_model = @descendants.select { |m| m.to_s == params['model_name'] }.first
    @current_model.load_schema
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy!
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show ]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/counter_helper.rb
module CounterHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
%div{id: dom_id(comment)}
  %p
    %strong User:
    = link_to comment.user.email, comment.user

  %p
    %strong Post:
    = link_to comment.post.id, comment.post

  %p
    %strong Body:
    = comment.body

app/views/comments/_form.html.haml
= form_with(model: comment) do |form|
  - if comment.errors.any?
    %div{style: "color: red"}
      %h2= "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"

      %ul
        - comment.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :user_id, style: "display: block"
    = form.number_field :user_id

  %div
    = form.label :post_id, style: "display: block"
    = form.number_field :post_id

  %div
    = form.label :body, style: "display: block"
    = form.textarea :body

  %div
    = form.submit

app/views/comments/edit.html.haml
- content_for :title, "Editing comment"

%h1 Editing comment

= render "form", comment: @comment

%br

%div
  = link_to "Show this comment", @comment
  |
  = link_to "Back to comments", comments_path

app/views/comments/index.html.haml
%p{style: "color: green"}= notice

- content_for :title, "Comments"

%h1 Comments

%div{id: "comments"}
  - @comments.each do |comment|
    = render comment
    %p
      = link_to "Show this comment", comment

= link_to "New comment", new_comment_path

app/views/comments/new.html.haml
- content_for :title, "New comment"

%h1 New comment

= render "form", comment: @comment

%br

%div
  = link_to "Back to comments", comments_path

app/views/comments/show.html.haml
%p{style: "color: green"}= notice

= render @comment

%div
  = link_to "Edit this comment", edit_comment_path(@comment)
  |
  = link_to "Back to comments", comments_path

  = button_to "Destroy this comment", @comment, method: :delete

app/views/counter/_elm.html.erb
<div id="counter">
  Please wait...
</div>

<%= javascript_include_tag "counter", "data-turbo-eval": "false" %>

<script>
 function loadElm(){
   var enode = document.getElementById("counter");
   if (enode)
   { var app = Elm.Counter.init({node: enode,
                                 flags: "no flags"})};
   // use ports and stuff here
 };
 document.addEventListener("DOMContentLoaded", loadElm);
</script>

app/views/counter/show.html.haml
%h1 Counter

= render partial: 'elm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Admin2"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "Admin2", :name => "application-name"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %p.tool_bar
      = link_to 'users', users_path
      \|
      = link_to 'posts', posts_path
      \|
      = link_to 'comments', comments_path
      \|
      = link_to 'counter', counter_path, data: {turbo: 'false'}
      \|
      = link_to 'models', models_index_path
      - if current_user.blank?
        \|
        = link_to 'login', new_user_session_path
      - if current_user.present?
        \|
        = link_to 'logout', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
        = current_user&.email

    -# we may not need those
    -# %p{class: 'notice'}= notice
    -# %p{class: 'alert'}= alert

    = yield

app/views/models/index.html.haml
%h1 Models#index
%p Find me in app/views/models/index.html.haml

%ul
  - @descendants.each do |d|
    %li
      = link_to (d.to_s), models_show_path(model_name: d.to_s)

app/views/models/show.html.haml
%h1
  Model
  = @current_model.to_s

%p= @current_model.inspect

%p
  Primary key:
  = @current_model.primary_key.inspect

%p= @current_model.methods.sort

app/views/posts/_form.html.haml
= form_with(model: post) do |form|
  - if post.errors.any?
    %div{style: "color: red"}
      %h2= "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"

      %ul
        - post.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :title, style: "display: block"
    = form.text_field :title

  %div
    = form.label :body, style: "display: block"
    = form.textarea :body

  %div
    = form.submit

app/views/posts/_post.html.haml
%div{id: dom_id(post)}
  %p
    %strong Title:
    = post.title

  %p
    %strong Body:
    = post.body

  - if post.user.present?
    %p
      %strong Author:
      = link_to post.user.email, post.user
  - else
    %p
      Ooops no author
  %p
    %strong Comments:
    = post.comments.count
  %div
    %table
      %tr
        %th link
        %th author
        %th body
      - post.comments.each do |c|
        %tr
          %td= link_to c.id.to_s, c
          %td= link_to c.user.email, c.user
          %td= c.body

app/views/posts/edit.html.haml
- content_for :title, "Editing post"

%h1 Editing post

= render "form", post: @post

%br

%div
  = link_to "Show this post", @post
  |
  = link_to "Back to posts", posts_path

app/views/posts/index.html.haml
%p{style: "color: green"}= notice

- content_for :title, "Posts"

%h1 Posts

%div{id: "posts"}
  - @posts.each do |post|
    = render post
    %p
      = link_to "Show this post", post
    %hr

= link_to "New post", new_post_path

app/views/posts/new.html.haml
- content_for :title, "New post"

%h1 New post

= render "form", post: @post

%br

%div
  = link_to "Back to posts", posts_path

app/views/posts/show.html.haml
%p{style: "color: green"}= notice

= render @post

%div
  = link_to "Edit this post", edit_post_path(@post)
  |
  = link_to "Back to posts", posts_path

  = button_to "Destroy this post", @post, method: :delete

app/views/users/_user.html.haml
%div{id: dom_id(user)}
  %p
    %strong Email:
    = user.email

  %p
    %strong ID:
    = user.id
    %br
    %strong created_at:
    = user.created_at

app/views/users/index.html.haml
%p{style: "color: green"}= notice

- content_for :email, "Users"

%h1 Users

%div{id: "users"}
  - @users.each do |user|
    = render user
    %p
      = link_to "Show this user", user
    %hr

app/views/users/show.html.haml
%p{style: "color: green"}= notice

= render @user

%div
  - @user.posts.each do |p|
    %p
      = link_to p.id.to_s, post_path
      %br
      = p.inspect
    %p= "post has #{p.comments.count} comments"

%div
  = link_to "Back to users", users_path